#!/usr/bin/env python -u
# -*- coding: utf-8 -*-
'''
Test templates
'''

import logging
import argparse
from os.path import isfile
import yaml
import sys
import pepa

# Get arguments
parser = argparse.ArgumentParser()
parser.add_argument('-c', '--config', default='/etc/salt/master', help='Configuration file')
parser.add_argument('-d', '--debug', action='store_true', help='Print debug info')
parser.add_argument('-s', '--show', action='store_true', help='Show result of template')
parser.add_argument('-t', '--teamcity', action='store_true', help='Output validation in TeamCity format')
parser.add_argument('-n', '--no-color', dest='color', action='store_false', help='No color output')
args = parser.parse_args()

# Create formatter
if args.color:
    try:
        import colorlog
        formatter = colorlog.ColoredFormatter("[%(log_color)s%(levelname)-8s%(reset)s] %(log_color)s%(message)s%(reset)s")
    except ImportError:
        formatter = logging.Formatter("[%(levelname)-8s] %(message)s")
else:
    formatter = logging.Formatter("[%(levelname)-8s] %(message)s")

# Create console handle
console = logging.StreamHandler()
console.setFormatter(formatter)

# Create logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.addHandler(console)

# Create logger for module
logger_pepa = logging.getLogger('pepa')
logger_pepa.setLevel(logging.DEBUG)
logger_pepa.addHandler(console)

# Load configuration file
if not isfile(args.config):
    logger.critical('Configuration file doesn\'t exist {0}'.format(args.config))
    sys.exit(1)

# Get configuration
conf = yaml.load(open(args.config).read())
loc = 0
for name in [e.keys()[0] for e in conf['ext_pillar']]:
    if name == 'pepa':
        break
    loc += 1

p = conf['ext_pillar'][loc]['pepa']
templ = pepa.Template(roots=conf['pepa_roots'], resource=p['resource'], sequence=p['sequence'])
templ.testit(show=args.show, teamcity=args.teamcity)
